Server:
  Runmode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8080/static
  UploadImageMaxSize: 5
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: xxxx
  Password: xxxxx
  Host: rxxxxxx:3306
  DBName: blog
  TablePrefix: blog
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: joy-blog
  Issuer: blog-service
  Expire: 7200
Email:
  Host: smtp.163.com
  Port: 465
  UserName: 13456327316@163.com
  Password: JAVEQZJCRMZIVLBH
  IsSSL: true
  From: 13456327316@163.com
  To:
    - 1003818507@qq.com